"""empty message

Revision ID: 10ef75926323
Revises: None
Create Date: 2016-06-28 22:28:19.792783

"""

# revision identifiers, used by Alembic.
revision = '10ef75926323'
down_revision = None

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('http_request_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('access_time', sa.DateTime(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('referer', sa.String(), nullable=True),
    sa.Column('forwarded_for', sa.String(), nullable=True),
    sa.Column('originating_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_http_request_log_access_time'), 'http_request_log', ['access_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', citext.CIText(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('verified', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('has_admin', sa.Boolean(), nullable=True),
    sa.Column('has_mod', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    op.create_index(op.f('ix_users_password'), 'users', ['password'], unique=True)
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', citext.CIText(), nullable=False),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language')
    )
    op.create_index(op.f('ix_language_changetime'), 'language', ['changetime'], unique=False)
    op.create_index(op.f('ix_language_changeuser'), 'language', ['changeuser'], unique=False)
    op.create_index(op.f('ix_language_language'), 'language', ['language'], unique=False)
    op.create_table('news__posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('seriesTopic', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news__posts_timestamp'), 'news__posts', ['timestamp'], unique=False)
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('orig_lang', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Float(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_story_changetime'), 'story', ['changetime'], unique=False)
    op.create_index(op.f('ix_story_changeuser'), 'story', ['changeuser'], unique=False)
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', citext.CIText(), nullable=False),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story', 'name')
    )
    op.create_index(op.f('ix_author_changetime'), 'author', ['changetime'], unique=False)
    op.create_index(op.f('ix_author_changeuser'), 'author', ['changeuser'], unique=False)
    op.create_index(op.f('ix_author_name'), 'author', ['name'], unique=False)
    op.create_table('covers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srcfname', sa.Text(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('chapter', sa.Float(), nullable=True),
    sa.Column('fragment', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_covers_changetime'), 'covers', ['changetime'], unique=False)
    op.create_index(op.f('ix_covers_changeuser'), 'covers', ['changeuser'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', citext.CIText(), nullable=False),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story', 'genre')
    )
    op.create_index(op.f('ix_genres_changetime'), 'genres', ['changetime'], unique=False)
    op.create_index(op.f('ix_genres_changeuser'), 'genres', ['changeuser'], unique=False)
    op.create_index(op.f('ix_genres_genre'), 'genres', ['genre'], unique=False)
    op.create_table('languagechanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', citext.CIText(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['language.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_languagechanges_changetime'), 'languagechanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_languagechanges_changeuser'), 'languagechanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_languagechanges_language'), 'languagechanges', ['language'], unique=False)
    op.create_index(op.f('ix_languagechanges_srccol'), 'languagechanges', ['srccol'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('series_id', sa.Integer(), nullable=True),
    sa.Column('source_ip', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.CheckConstraint('(user_id IS NOT NULL AND source_ip IS NULL) OR (user_id IS NULL AND source_ip IS NOT NULL)', name='rating_src'),
    sa.CheckConstraint('rating <= 10', name='rating_max'),
    sa.CheckConstraint('rating >=  0', name='rating_min'),
    sa.ForeignKeyConstraint(['series_id'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'source_ip', 'series_id')
    )
    op.create_index(op.f('ix_ratings_series_id'), 'ratings', ['series_id'], unique=False)
    op.create_index(op.f('ix_ratings_source_ip'), 'ratings', ['source_ip'], unique=False)
    op.create_index(op.f('ix_ratings_user_id'), 'ratings', ['user_id'], unique=False)
    op.create_table('serieschanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('orig_lang', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Float(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['story.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_serieschanges_changetime'), 'serieschanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_serieschanges_changeuser'), 'serieschanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_serieschanges_srccol'), 'serieschanges', ['srccol'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('tag', citext.CIText(), nullable=False),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story', 'tag')
    )
    op.create_index(op.f('ix_tags_changetime'), 'tags', ['changetime'], unique=False)
    op.create_index(op.f('ix_tags_changeuser'), 'tags', ['changeuser'], unique=False)
    op.create_index(op.f('ix_tags_tag'), 'tags', ['tag'], unique=False)
    op.create_table('authorchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', citext.CIText(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['author.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorchanges_changetime'), 'authorchanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_authorchanges_changeuser'), 'authorchanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_authorchanges_name'), 'authorchanges', ['name'], unique=False)
    op.create_index(op.f('ix_authorchanges_srccol'), 'authorchanges', ['srccol'], unique=False)
    op.create_table('coverschanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('srcfname', sa.Text(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('chapter', sa.Float(), nullable=True),
    sa.Column('fragment', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['covers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coverschanges_changetime'), 'coverschanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_coverschanges_changeuser'), 'coverschanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_coverschanges_srccol'), 'coverschanges', ['srccol'], unique=False)
    op.create_table('genreschanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('genre', citext.CIText(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['genres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genreschanges_changetime'), 'genreschanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_genreschanges_changeuser'), 'genreschanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_genreschanges_genre'), 'genreschanges', ['genre'], unique=False)
    op.create_index(op.f('ix_genreschanges_srccol'), 'genreschanges', ['srccol'], unique=False)
    op.create_table('tagschanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('tag', citext.CIText(), nullable=False),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['tags.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagschanges_changetime'), 'tagschanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_tagschanges_changeuser'), 'tagschanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_tagschanges_srccol'), 'tagschanges', ['srccol'], unique=False)
    op.create_index(op.f('ix_tagschanges_tag'), 'tagschanges', ['tag'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tagschanges_tag'), table_name='tagschanges')
    op.drop_index(op.f('ix_tagschanges_srccol'), table_name='tagschanges')
    op.drop_index(op.f('ix_tagschanges_changeuser'), table_name='tagschanges')
    op.drop_index(op.f('ix_tagschanges_changetime'), table_name='tagschanges')
    op.drop_table('tagschanges')
    op.drop_index(op.f('ix_genreschanges_srccol'), table_name='genreschanges')
    op.drop_index(op.f('ix_genreschanges_genre'), table_name='genreschanges')
    op.drop_index(op.f('ix_genreschanges_changeuser'), table_name='genreschanges')
    op.drop_index(op.f('ix_genreschanges_changetime'), table_name='genreschanges')
    op.drop_table('genreschanges')
    op.drop_index(op.f('ix_coverschanges_srccol'), table_name='coverschanges')
    op.drop_index(op.f('ix_coverschanges_changeuser'), table_name='coverschanges')
    op.drop_index(op.f('ix_coverschanges_changetime'), table_name='coverschanges')
    op.drop_table('coverschanges')
    op.drop_index(op.f('ix_authorchanges_srccol'), table_name='authorchanges')
    op.drop_index(op.f('ix_authorchanges_name'), table_name='authorchanges')
    op.drop_index(op.f('ix_authorchanges_changeuser'), table_name='authorchanges')
    op.drop_index(op.f('ix_authorchanges_changetime'), table_name='authorchanges')
    op.drop_table('authorchanges')
    op.drop_index(op.f('ix_tags_tag'), table_name='tags')
    op.drop_index(op.f('ix_tags_changeuser'), table_name='tags')
    op.drop_index(op.f('ix_tags_changetime'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_serieschanges_srccol'), table_name='serieschanges')
    op.drop_index(op.f('ix_serieschanges_changeuser'), table_name='serieschanges')
    op.drop_index(op.f('ix_serieschanges_changetime'), table_name='serieschanges')
    op.drop_table('serieschanges')
    op.drop_index(op.f('ix_ratings_user_id'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_source_ip'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_series_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_languagechanges_srccol'), table_name='languagechanges')
    op.drop_index(op.f('ix_languagechanges_language'), table_name='languagechanges')
    op.drop_index(op.f('ix_languagechanges_changeuser'), table_name='languagechanges')
    op.drop_index(op.f('ix_languagechanges_changetime'), table_name='languagechanges')
    op.drop_table('languagechanges')
    op.drop_index(op.f('ix_genres_genre'), table_name='genres')
    op.drop_index(op.f('ix_genres_changeuser'), table_name='genres')
    op.drop_index(op.f('ix_genres_changetime'), table_name='genres')
    op.drop_table('genres')
    op.drop_index(op.f('ix_covers_changeuser'), table_name='covers')
    op.drop_index(op.f('ix_covers_changetime'), table_name='covers')
    op.drop_table('covers')
    op.drop_index(op.f('ix_author_name'), table_name='author')
    op.drop_index(op.f('ix_author_changeuser'), table_name='author')
    op.drop_index(op.f('ix_author_changetime'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_story_changeuser'), table_name='story')
    op.drop_index(op.f('ix_story_changetime'), table_name='story')
    op.drop_table('story')
    op.drop_index(op.f('ix_news__posts_timestamp'), table_name='news__posts')
    op.drop_table('news__posts')
    op.drop_index(op.f('ix_language_language'), table_name='language')
    op.drop_index(op.f('ix_language_changeuser'), table_name='language')
    op.drop_index(op.f('ix_language_changetime'), table_name='language')
    op.drop_table('language')
    op.drop_index(op.f('ix_users_password'), table_name='users')
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_http_request_log_access_time'), table_name='http_request_log')
    op.drop_table('http_request_log')
    ### end Alembic commands ###
