"""empty message

Revision ID: 580403142547
Revises: 5e32d3d7cf49
Create Date: 2016-07-07 20:36:24.992797

"""

# revision identifiers, used by Alembic.
revision = '580403142547'
down_revision = '5e32d3d7cf49'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('serieschanges', sa.Column('downloads', sa.Integer(), nullable=True))
    op.add_column('story', sa.Column('downloads', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'downloads')
    op.drop_column('serieschanges', 'downloads')
    ### end Alembic commands ###
