"""empty message

Revision ID: 5e32d3d7cf49
Revises: 10ef75926323
Create Date: 2016-07-02 13:35:56.415918

"""

# revision identifiers, used by Alembic.
revision = '5e32d3d7cf49'
down_revision = '10ef75926323'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coverschanges')
    op.drop_table('covers')
    op.add_column('serieschanges', sa.Column('srcfname', sa.Text(), nullable=True))
    op.add_column('story', sa.Column('srcfname', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story', 'srcfname')
    op.drop_column('serieschanges', 'srcfname')
    op.create_table('coverschanges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('srcfname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chapter', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fragment', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('operation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('srccol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('story', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changeuser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], name='coverschanges_changeuser_fkey'),
    sa.ForeignKeyConstraint(['srccol'], ['covers.id'], name='coverschanges_srccol_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], name='coverschanges_story_fkey'),
    sa.PrimaryKeyConstraint('id', name='coverschanges_pkey')
    )
    op.create_table('covers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('srcfname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('volume', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chapter', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fragment', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('story', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changeuser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], name='covers_changeuser_fkey'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], name='covers_story_fkey'),
    sa.PrimaryKeyConstraint('id', name='covers_pkey')
    )
    ### end Alembic commands ###
