"""empty message

Revision ID: 8b91fbcd0a32
Revises: 580403142547
Create Date: 2016-07-07 21:00:12.289189

"""

# revision identifiers, used by Alembic.
revision = '8b91fbcd0a32'
down_revision = '580403142547'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ratingschanges',
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', citext.CIText(), nullable=False),
    sa.Column('source_ip', sa.Text(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.Column('be_ctnt', sa.Integer(), nullable=False),
    sa.Column('chars_ctnt', sa.Integer(), nullable=False),
    sa.Column('technical', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('story', sa.Integer(), nullable=False),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['ratings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story'], ['story.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratingschanges_changetime'), 'ratingschanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_ratingschanges_changeuser'), 'ratingschanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_ratingschanges_source_ip'), 'ratingschanges', ['source_ip'], unique=False)
    op.create_index(op.f('ix_ratingschanges_srccol'), 'ratingschanges', ['srccol'], unique=False)
    op.create_index(op.f('ix_ratingschanges_story'), 'ratingschanges', ['story'], unique=False)
    op.create_index(op.f('ix_ratingschanges_user_id'), 'ratingschanges', ['user_id'], unique=False)
    op.add_column('ratings', sa.Column('be_ctnt', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('changetime', sa.DateTime(), nullable=False))
    op.add_column('ratings', sa.Column('changeuser', sa.Integer(), nullable=True))
    op.add_column('ratings', sa.Column('chars_ctnt', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('comments', sa.Text(), nullable=False))
    op.add_column('ratings', sa.Column('nickname', citext.CIText(), nullable=False))
    op.add_column('ratings', sa.Column('overall', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('story', sa.Integer(), nullable=False))
    op.add_column('ratings', sa.Column('technical', sa.Integer(), nullable=False))
    op.alter_column('ratings', 'source_ip',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_index(op.f('ix_ratings_changetime'), 'ratings', ['changetime'], unique=False)
    op.create_index(op.f('ix_ratings_changeuser'), 'ratings', ['changeuser'], unique=False)
    op.create_index(op.f('ix_ratings_story'), 'ratings', ['story'], unique=False)
    op.drop_index('ix_ratings_series_id', table_name='ratings')
    op.drop_constraint('ratings_user_id_source_ip_series_id_key', 'ratings', type_='unique')
    op.create_unique_constraint(None, 'ratings', ['story', 'nickname'])
    op.drop_constraint('ratings_series_id_fkey', 'ratings', type_='foreignkey')
    op.create_foreign_key(None, 'ratings', 'users', ['changeuser'], ['id'])
    op.create_foreign_key(None, 'ratings', 'story', ['story'], ['id'])
    op.drop_column('ratings', 'series_id')
    op.drop_column('ratings', 'rating')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ratings', sa.Column('rating', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('ratings', sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.create_foreign_key('ratings_series_id_fkey', 'ratings', 'story', ['series_id'], ['id'])
    op.drop_constraint(None, 'ratings', type_='unique')
    op.create_unique_constraint('ratings_user_id_source_ip_series_id_key', 'ratings', ['user_id', 'source_ip', 'series_id'])
    op.create_index('ix_ratings_series_id', 'ratings', ['series_id'], unique=False)
    op.drop_index(op.f('ix_ratings_story'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_changeuser'), table_name='ratings')
    op.drop_index(op.f('ix_ratings_changetime'), table_name='ratings')
    op.alter_column('ratings', 'source_ip',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('ratings', 'technical')
    op.drop_column('ratings', 'story')
    op.drop_column('ratings', 'overall')
    op.drop_column('ratings', 'nickname')
    op.drop_column('ratings', 'comments')
    op.drop_column('ratings', 'chars_ctnt')
    op.drop_column('ratings', 'changeuser')
    op.drop_column('ratings', 'changetime')
    op.drop_column('ratings', 'be_ctnt')
    op.drop_index(op.f('ix_ratingschanges_user_id'), table_name='ratingschanges')
    op.drop_index(op.f('ix_ratingschanges_story'), table_name='ratingschanges')
    op.drop_index(op.f('ix_ratingschanges_srccol'), table_name='ratingschanges')
    op.drop_index(op.f('ix_ratingschanges_source_ip'), table_name='ratingschanges')
    op.drop_index(op.f('ix_ratingschanges_changeuser'), table_name='ratingschanges')
    op.drop_index(op.f('ix_ratingschanges_changetime'), table_name='ratingschanges')
    op.drop_table('ratingschanges')
    ### end Alembic commands ###
