"""empty message

Revision ID: a9f602b9170d
Revises: d28d1008931f
Create Date: 2018-03-04 08:11:35.543399

"""

# revision identifiers, used by Alembic.
revision = 'a9f602b9170d'
down_revision = 'd28d1008931f'

from alembic import op
import sqlalchemy as sa
import citext


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story', sa.Column('story_html', sa.Text(), nullable=True))
    op.add_column('storychanges', sa.Column('story_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('storychanges', 'story_html')
    op.drop_column('story', 'story_html')
    # ### end Alembic commands ###
