"""empty message

Revision ID: d28d1008931f
Revises: 8b91fbcd0a32
Create Date: 2016-07-10 21:32:14.150071

"""

# revision identifiers, used by Alembic.
revision = 'd28d1008931f'
down_revision = '8b91fbcd0a32'

from alembic import op
import sqlalchemy as sa
import citext
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storychanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', citext.CIText(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('orig_lang', sa.Text(), nullable=True),
    sa.Column('chapter', sa.Float(), nullable=True),
    sa.Column('pub_date', sa.DateTime(), nullable=True),
    sa.Column('srcfname', sa.Text(), nullable=True),
    sa.Column('fspath', sa.Text(), nullable=True),
    sa.Column('hash', sa.Text(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=True),
    sa.Column('srccol', sa.Integer(), nullable=True),
    sa.Column('changeuser', sa.Integer(), nullable=True),
    sa.Column('changetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], ),
    sa.ForeignKeyConstraint(['srccol'], ['story.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storychanges_changetime'), 'storychanges', ['changetime'], unique=False)
    op.create_index(op.f('ix_storychanges_changeuser'), 'storychanges', ['changeuser'], unique=False)
    op.create_index(op.f('ix_storychanges_srccol'), 'storychanges', ['srccol'], unique=False)
    op.drop_table('serieschanges')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serieschanges',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', citext.CIText(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('orig_lang', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chapter', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('pub_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('fspath', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hash', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('operation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('srccol', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changeuser', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('changetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('srcfname', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['changeuser'], ['users.id'], name='serieschanges_changeuser_fkey'),
    sa.ForeignKeyConstraint(['srccol'], ['story.id'], name='serieschanges_srccol_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='serieschanges_pkey')
    )
    op.drop_index(op.f('ix_storychanges_srccol'), table_name='storychanges')
    op.drop_index(op.f('ix_storychanges_changeuser'), table_name='storychanges')
    op.drop_index(op.f('ix_storychanges_changetime'), table_name='storychanges')
    op.drop_table('storychanges')
    ### end Alembic commands ###
